# Artificial Neural Network

### Importing the libraries

In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [30]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

# Importing the dataset

In [31]:
dataset = pd.read_csv('Churn_Modelling.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [32]:
print(len(x),len(y))

10000 10000


In [33]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [34]:
print(y)

[1 0 1 ... 1 1 0]


Taking care of missing values

In [35]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [36]:
#No missing values in any column

### Encoding categorical data

Label Encoding the "Gender" column

In [37]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
x[:,2]=lb.fit_transform(x[:,2])

In [38]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

One Hot Encoding the "Geography" column

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [40]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

### Feature Scaling

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [43]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [44]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
#Creating fully connected layer using dense class 

### Adding the second hidden layer

In [45]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
#Creating fully connected layer using dense class 

### Adding the output layer

In [46]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
#for non classification use 'softmax' for activation function

## Part 3 - Training the ANN

### Compiling the ANN

In [49]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#optimizer= for stochastic or batch gradient system
#loss= for binary binary_crossentropy for more than 2 class use 'cat_crossentropy'
#metrics=

### Training the ANN on the Training set

In [50]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5608 - accuracy: 0.7906
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4735 - accuracy: 0.7945
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4456 - accuracy: 0.7945
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4359 - accuracy: 0.7945
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4310 - accuracy: 0.7945
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4278 - accuracy: 0.7945
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4253 - accuracy: 0.7944
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4224 - accuracy: 0.7966
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4202 - accuracy: 0.8104
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4178 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

In [53]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,50000]]))>0.5)
# 1 = Leaves the bank
# 0 =  Does not leave the bank

[[False]]


### Predicting the Test set results

In [54]:
y_pred = ann.predict(x_test)
y_pred = (y_pred)>0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 1]
 [0 1]]


In [55]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.86


### Making the Confusion Matrix

In [56]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1541   66]
 [ 214  179]]
